### ISSUE TITLE
Errors loading this plugin

### ISSUE THREAD

**Issue by D3XX3R** [2547techno/chat-commands-plus#1]
When loading the metadata for this plugin, I receive the following error:
`permissions element #0: permission type is an unknown (Network)`

**Comment by 2547techno** [comment]
The `Network` permission was only recently added, you need to update your chatterino to a version after [this commit](https://github.com/Chatterino/chatterino2/commit/c980162656aa7d98ee1b11e050350c4d351ab6ca). There is no stable release that has this at the moment, you must install [a nightly build](https://github.com/Chatterino/chatterino2/releases/tag/nightly-build).

Let me know if this fixed the issue!

**Comment by D3XX3R** [comment]
Works now that I got the nightly build. Thanks a lot for clarifying!
